<?php

namespace app\modules;

use yii\base\Module as BaseModule;
use yii\filters\Cors;
use yii\filters\VerbFilter;

class Module extends BaseModule
{
    public function init()
    {
        $this->modules = [
            "v1" => v1\Module::className()
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['corsFilter'] = [
            'class' => Cors::class, // the new Cors class inherited from yii2's
            'cors' => [
                'Origin' => ['*'],
                'Access-Control-Request-Method' => ['GET', 'POST', 'OPTIONS', 'DELETE', 'PATCH'],
                'Access-Control-Request-Headers' => ['Origin', 'X-Requested-With', 'Content-Type', 'accept', 'Authorization', 'G-ClientID', 'UserIP'],
            ],
        ];
        /* Default Validate Method */
        $behaviors["verbFilter"] = [
            'class' => VerbFilter::className(),
            'actions' => [
                'index' => ['GET'],
                'update' => ['POST'],
                'view' => ['GET'],
                'delete' => ['POST', 'DELETE'],
                'delete-many' => ['POST', 'DELETE'],
                'create' => ['POST']
            ]
        ];

        return $behaviors;
    }
}