<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\ProductVariantQuery;

/**
 * This is the base-model class for table "product_variants".
 *
 * @property integer $id
 * @property integer $product_id
 * @property string $name
 * @property string $value
 * @property integer $stock
 * @property double $price
 * @property integer $status
 * @property string $created_at
 * @property string $updated_at
 */
abstract class ProductVariant extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_variants';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['product_id', 'name', 'value', 'stock', 'price', 'status'], 'default', 'value' => null],
            [['product_id', 'stock', 'status'], 'integer'],
            [['price'], 'number'],
            [['name', 'value'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'product_id' => 'Product ID',
            'name' => 'Name',
            'value' => 'Value',
            'stock' => 'Stock',
            'price' => 'Price',
            'status' => 'Status',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return ProductVariantQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ProductVariantQuery(static::class);
    }
}
