<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;
use yii\helpers\ArrayHelper;
use yii\behaviors\TimestampBehavior;
use \app\models\UserQuery;

/**
 * This is the base-model class for table "user".
 *
 * @property integer $id
 * @property string $token
 * @property string $email
 * @property string $username
 * @property integer $status
 * @property string $password_hash
 * @property string $logged_at
 * @property string $created_at
 * @property string $updated_at
 */
abstract class User extends \yii\db\ActiveRecord
{

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $behaviors = parent::behaviors();
        $behaviors['timestamp'] = [
            'class' => TimestampBehavior::class,
            'value' => (new \DateTime())->format('Y-m-d H:i:s'),
                        ];
        
    return $behaviors;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $parentRules = parent::rules();
        return ArrayHelper::merge($parentRules, [
            [['token', 'email', 'username', 'status', 'password_hash', 'logged_at'], 'default', 'value' => null],
            [['status'], 'integer'],
            [['logged_at'], 'safe'],
            [['token', 'email', 'username', 'password_hash'], 'string', 'max' => 255]
        ]);
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return ArrayHelper::merge(parent::attributeLabels(), [
            'id' => 'ID',
            'token' => 'Token',
            'email' => 'Email',
            'username' => 'Username',
            'status' => 'Status',
            'password_hash' => 'Password Hash',
            'logged_at' => 'Logged At',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ]);
    }

    /**
     * @inheritdoc
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(static::class);
    }
}
